package com.qr.qrcode.barcode.scanner.reader.qreader.android.designsystem.localization

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf

val LocalStrings = staticCompositionLocalOf { stringResourcesEn() }

@Immutable
data class StringResources(
    val appName: String = "QReader",
    val cancel: String = "Cancel",
    val actionContinue: String = "Continue",
    val create: String = "Create",
    val delete: String = "Delete",
    val next: String = "Next",
    val ok: String = "OK",
    val preview: String = "Preview",
    val save: String = "Save",
    val scan: String = "Scan",
    val select: String = "Select",
    val selectLocation: String = "Select location",
    val sendUs: String = "Send us an email",
    val share: String = "Share",
    val skip: String = "Skip",
    val start: String = "Start",
    val addContent: String = "Add content",
    val addLogo: String = "Add logo",
    val address: String = "Address",
    val alignQrCode: String = "Align QR Code / Bardcode within frame to scan",
    val allDayEvent: String = "All day event",
    val allowCameraAccess: String = "Allow Camera Access",
    val allowLocationAccess: String = "Allow Location Access",
    val allowStorageAccess: String = "Allow Storage Access",
    val appVersion: String = "App Version",
    val backgroundColor: String = "Background Color",
    val batchScan: String = "Batch Scan",
    val cancelAnytime: String = "No commitments, cancel anytime!",
    val chromeCustomTabs: String = "Chrome Custom Tabs",
    val clickCreateButton: String = "Click create button to start create QR Code.",
    val clickScanButton: String = "Click scan button to start scan QR Code.",
    val color: String = "Color",
    val communication: String = "Communication",
    val companyName: String = "Company name",
    val cornerStyle: String = "Corner style",
    val created: String = "Created",
    val creator: String = "Creator",
    val customize: String = "Customize",
    val customizeQr: String = "Customize QR",
    val dark: String = "Dark",
    val description: String = "Description",
    val dotColor: String = "Dot color",
    val dotsColor: String = "Dots color",
    val dotsStyle: String = "Dots style",
    val egPlaceholderAddress: String = "e.g. New York City, Spring Avenue, 9/18",
    val egPlaceholderCompanyName: String = "e.g. My Company",
    val egPlaceholderDate: String = "e.g 12 Dec 2024",
    val egPlaceholderDateTime: String = "e.g 12 Dec 2024, 10:40",
    val egPlaceholderEmail: String = "e.g. name@email.com",
    val egPlaceholderEventDescription: String = "e.g. Celebrate the queen of our hearts! Join us in honoring our beloved mother on her special day.",
    val egPlaceholderEventName: String = "e.g. Birthday mother",
    val egPlaceholderFirstName: String = "e.g. Paul",
    val egPlaceholderIndustry: String = "e.g. Animation Studio",
    val egPlaceholderJob: String = "e.g. Android Developer",
    val egPlaceholderLastName: String = "e.g. Jones",
    val egPlaceholderLatitude: String = "e.g. 24.467035",
    val egPlaceholderLocation: String = "e.g. Rooftop Restaurant - Skyline Bistro",
    val egPlaceholderLongitude: String = "e.g. 39.610947",
    val egPlaceholderPhone: String = "e.g. +1809999999",
    val egPlaceholderSmsMessage: String = "e.g. Running late. Be there in 10 mins.",
    val egPlaceholderSubject: String = "e.g. QReader app",
    val egPlaceholderText: String = "e.g. Discover the ancient Silk Road in Uzbekistan.",
    val egPlaceholderWebsite: String = "e.g. www.yourwebsite.com",
    val egPlaceholderWifiName: String = "e.g. My Wi-Fi",
    val egPlaceholderWifiPassword: String = "e.g. 11111111",
    val emailAddress: String = "Email address",
    val encryptionType: String = "Encryption type",
    val endDate: String = "End date",
    val endDateTime: String = "End date and time",
    val enterValue: String = "Enter value",
    val eventName: String = "Event name",
    val failedToSaveImage: String = "Failed to save image",
    val faq: String = "FAQ",
    val feature1: String = "Unlimited CSV Exports",
    val feature2: String = "Code Color Custom",
    val feature3: String = "Fast and Secure Batch Scan",
    val feature4: String = "No Ads!",
    val feedback: String = "Feedback",
    val feedbackDescription: String = "Many questions are already answered in the \"FAQ\".\n\nPlease write your email in English.\n\nIf possible, please include photos of the barcode or screenshots.",
    val name: String = "Name",
    val frameColor: String = "Frame color",
    val frameStyle: String = "Frame style",
    val frequentlyAskedQuestions: String = "Frequently Asked Questions",
    val general: String = "General",
    val getHelp: String = "Get Help",
    val goPro: String = "Go Pro!",
    val grantCameraPermission: String = "Grant Camera Permission for QR Codes.",
    val grantLocationPermission: String = "Grant Location permission for enhanced QR scanning accuracy.",
    val grantStoragePermission: String = "Grant Storage permission to save the QR image so you can easily access and share it whenever necessary.",
    val helpUsImprove: String = "Help us improve!",
    val hidden: String = "Hidden",
    val history: String = "History",
    val imageSavedToGallery: String = "Image saved to gallery",
    val industry: String = "Industry",
    val job: String = "Job",
    val language: String = "Language",
    val lastName: String = "Last name",
    val latitude: String = "Latitude",
    val library: String = "Library",
    val light: String = "Light",
    val location: String = "Location",
    val longitude: String = "Longitude",
    val managePermissions: String = "Manage Permissions",
    val maximumSize: String = "Maximum size: 2 MB",
    val message: String = "Message",
    val networkName: String = "Network name",
    val noContentFound: String = "No content found!",
    val onboardingDescription1: String = "Edit and change your QR codes anytime.",
    val onboardingDescription2: String = "Track your QR codes and get insights about scans.",
    val onboardingDescription3: String = "Create and edit many QR codes in no time.",
    val onboardingDescription4: String = "Create transparent QR codes and reusable design templates.",
    val onboardingTitle1: String = "Dynamic QR Codes",
    val onboardingTitle2: String = "Scan Statistics",
    val onboardingTitle3: String = "Bulk Creation and Editing",
    val onboardingTitle4: String = "More Design Options",
    val openWebPages: String = "Open web pages automatically",
    val other: String = "Other",
    val others: String = "Others",
    val password: String = "Password",
    val permissionsGranted: String = "Permission granted!",
    val permissionsGrantedDescription: String = "You now have complete access to our QReader app. Get ready to scan, generate and share QR codes with ease.",
    val phoneNumber: String = "Phone number",
    val premium: String = "Premium",
    val premiumDescription: String = "You can be premium by choosing a package and you can create the qr code you want and customize it as you wish.",
    val privacy: String = "Privacy",
    val qrCode: String = "QR Code",
    val qrCodePattern: String = "QR code pattern",
    val rateUs: String = "Rate us",
    val scanControls: String = "Scan controls",
    val scanned: String = "Scanned",
    val scanner: String = "Scanner",
    val searchQrCode: String = "Search QR Code",
    val selectDate: String = "Select date",
    val selectDateAndTime: String = "Select Date and Time",
    val selectTime: String = "Select time",
    val settings: String = "Settings",
    val socialMedia: String = "Social Media",
    val soundEffects: String = "Sound Effects",
    val startDate: String = "Start date",
    val startDateTime: String = "Start date and time",
    val subject: String = "Subject",
    val systemDefault: String = "System default",
    val tellFriends: String = "Tell friends",
    val terms: String = "Terms",
    val text: String = "Text",
    val theme: String = "Theme",
    val uploadImage: String = "Upload image (JPG and PNG)",
    val uploadYourOwnLogo: String = "Upload your own logo",
    val vibrate: String = "Vibrate",
    val web: String = "Web",
    val website: String = "Website",
    val welcomeToPremium: String = "Welcome to Premium!",
    val whatsappNumber: String = "WhatsApp number",
    val searchOnWeb: String = "Search on the web",
    val openWebsite: String = "Open website",
    val sendSms: String = "Send SMS",
    val sendEmail: String = "Send email",
    val addContact: String = "Add contact",
) {

    fun socialMediaChannel(channel: String): String {
        return "$channel channel name"
    }

    fun socialMediaProfile(profile: String): String {
        return "$profile profile"
    }

    fun socialMediaUsername(username: String): String {
        return "$username username"
    }
}