package com.qr.qrcode.barcode.scanner.reader.qreader.android.design.localization

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf

val LocalStrings = staticCompositionLocalOf { stringResourcesEn() }

@Immutable
data class StringResources(
    val appName: String = "QReader",
    val cancel: String,
    val actionContinue: String,
    val create: String,
    val delete: String,
    val next: String,
    val ok: String,
    val preview: String,
    val save: String,
    val scan: String,
    val select: String,
    val selectLocation: String,
    val sendUs: String,
    val telegramBot: String = "Telegram Bot",
    val share: String,
    val skip: String,
    val start: String,
    val addContent: String,
    val addLogo: String,
    val address: String,
    val alignQrCode: String,
    val allDayEvent: String,
    val allowCameraAccess: String,
    val allowLocationAccess: String,
    val allowStorageAccess: String,
    val appVersion: String,
    val backgroundColor: String,
    val batchScan: String,
    val cancelAnytime: String,
    val chromeCustomTabs: String,
    val clickCreateButton: String,
    val clickScanButton: String,
    val color: String,
    val communication: String,
    val companyName: String,
    val cornerStyle: String,
    val created: String,
    val creator: String,
    val customize: String,
    val customizeQr: String,
    val dark: String,
    val description: String,
    val dotColor: String,
    val dotsColor: String,
    val dotsStyle: String,
    val egPlaceholderAddress: String,
    val egPlaceholderCompanyName: String,
    val egPlaceholderDate: String,
    val egPlaceholderDateTime: String,
    val egPlaceholderEmail: String,
    val egPlaceholderEventDescription: String,
    val egPlaceholderEventName: String,
    val egPlaceholderFirstName: String,
    val egPlaceholderIndustry: String,
    val egPlaceholderJob: String,
    val egPlaceholderLastName: String,
    val egPlaceholderLatitude: String,
    val egPlaceholderLocation: String,
    val egPlaceholderLongitude: String,
    val egPlaceholderPhone: String,
    val egPlaceholderSmsMessage: String,
    val egPlaceholderSubject: String,
    val egPlaceholderText: String,
    val egPlaceholderWebsite: String,
    val egPlaceholderWifiName: String,
    val egPlaceholderWifiPassword: String,
    val emailAddress: String,
    val encryptionType: String,
    val endDate: String,
    val endDateTime: String,
    val enterValue: String,
    val eventName: String,
    val faq: String,
    val feature1: String,
    val feature2: String,
    val feature3: String,
    val feature4: String,
    val feedback: String,
    val feedbackDescription: String,
    val name: String,
    val frameColor: String,
    val frameStyle: String,
    val frequentlyAskedQuestions: String,
    val general: String,
    val getHelp: String,
    val goPro: String,
    val grantCameraPermission: String,
    val grantLocationPermission: String,
    val grantStoragePermission: String,
    val helpUsImprove: String,
    val hidden: String,
    val history: String,
    val industry: String,
    val job: String,
    val language: String,
    val lastName: String,
    val latitude: String,
    val library: String,
    val light: String,
    val location: String,
    val longitude: String,
    val managePermissions: String,
    val maximumSize: String,
    val message: String,
    val networkName: String,
    val noContentFound: String,
    val onboardingDescription1: String,
    val onboardingDescription2: String,
    val onboardingDescription3: String,
    val onboardingDescription4: String,
    val onboardingTitle1: String,
    val onboardingTitle2: String,
    val onboardingTitle3: String,
    val onboardingTitle4: String,
    val openWebPages: String,
    val other: String,
    val others: String,
    val password: String,
    val permissionsGranted: String,
    val permissionsGrantedDescription: String,
    val phoneNumber: String,
    val premium: String,
    val premiumDescription: String,
    val privacy: String,
    val qrCode: String,
    val qrCodePattern: String,
    val rateUs: String,
    val scanControls: String,
    val scanned: String,
    val scanner: String,
    val searchQrCode: String,
    val selectDate: String,
    val selectDateAndTime: String,
    val selectTime: String,
    val settings: String,
    val socialMedia: String,
    val startDate: String,
    val startDateTime: String,
    val subject: String,
    val systemDefault: String,
    val tellFriends: String,
    val terms: String,
    val text: String,
    val theme: String,
    val uploadImage: String,
    val uploadYourOwnLogo: String,
    val vibrate: String,
    val web: String,
    val website: String,
    val welcomeToPremium: String,
    val whatsappNumber: String,
    val searchOnWeb: String,
    val openWebsite: String,
    val sendSms: String,
    val sendEmail: String,
    val addContact: String,
    val showLocation: String,
    val shareDescription: String,
    val connectToWifi: String,
    val copyNetworkName: String,
    val copyPassword: String,
    val copy: String,
    val edit: String,
    val mChannelName: String,
    val mProfile: String,
    val mUsername: String,
    val mDial: String,
    val viewAddress: String,
    val addToCalendar: String,
    val scanImage: String,
    val dragMarkers: String,
) {

    fun socialMediaChannel(channel: String): String {
        return "$channel $mChannelName"
    }

    fun socialMediaProfile(profile: String): String {
        return "$profile $mProfile"
    }

    fun socialMediaUsername(username: String): String {
        return "$username $mUsername"
    }

    fun dial(phone: String): String {
        return "$mDial $phone"
    }
}