plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace = "com.github.alexzhirkevich.customqrgenerator"
    compileSdk 33

    defaultConfig {
        minSdk 24
        targetSdk 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    kotlin {
        jvmToolchain(17)
    }
}

dependencies {
    implementation(libs.kotlin.coroutines)
    implementation(libs.androidx.core)
    implementation(libs.google.zxing)
}