package com.qr.qrcode.barcode.scanner.reader.qreader.core.helpers

object StringRes {
    const val text = "Simple Text"
    const val website = "Website URL"
    const val wifi = "Wi-Fi"
    const val calendarEvent = "Calendar Event"
    const val bizCard = "Biz card"
    const val contactVCard = "Contact - vCard"
    const val businessVCard = "Business - vCard"
    const val location = "Location"
    const val phoneNumber = "Phone Number"
    const val sms = "SMS"
    const val emailAddress = "Email Address"
    const val youtube = "YouTube"
    const val whatsApp = "WhatsApp"
    const val instagram = "Instagram"
    const val facebook = "Facebook"
    const val twitter = "Twitter"
    const val tiktok = "TikTok "
    const val telegram = "Telegram"
    const val vkontakte = "ВКонтакте"
    const val twitch = "Twitch"
    const val linkedin = "LinkedIn"
    const val github = "Github"
    const val medium = "Medium"
    const val dribbble = "Dribbble"
    const val behance = "Behance"

    const val copiedText = "Copied Text"
    const val copiedToClipboard = "Copied to clipboard"
    const val sendEmail = "Send email"
    const val photoSaved = "Photo saved successfully"
}